from PySide6.QtCore import QSize

SUB_DIVIDE_INCR = 50
DIVISIONS_BAR_HEIGHT = 70
TICK_HEIGHT = 25
LEFT_PANEL_WIDTH = 300
TRACK_VIEW_HEIGHT = 800
GRID_SPACE = QSize(SUB_DIVIDE_INCR, SUB_DIVIDE_INCR - 10)
