from PySide6.QtCore import QSize

SUB_DIVIDE_INCR = 50
DIVISIONS_BAR_HEIGHT = 70
TICK_HEIGHT = 25
LEFT_PANEL_WIDTH = 300
TRACK_VIEW_HEIGHT = 800
GRID_WIDTH = SUB_DIVIDE_INCR
GRID_HEIGHT = SUB_DIVIDE_INCR - 20
GRID_SPACE = QSize(GRID_WIDTH, GRID_HEIGHT)
